version: '3.8'

services:
  # Vector Database for Development
  chroma:
    image: chromadb/chroma:latest
    container_name: ai-pdf-chroma-dev
    ports:
      - "8000:8000"
    volumes:
      - chroma_dev_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ai-pdf-dev-network

volumes:
  chroma_dev_data:
    driver: local

networks:
  ai-pdf-dev-network:
    driver: bridge
